name: Build and test

on: [push, pull_request]

env:
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  macosx-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install \
            autoconf \
            automake \
            bison \
            flex \
            libtool \
            pkg-config \
            jansson \
            libmagic \
            openssl@3 \
            file
      - name: Print versions
        run: |
          bison --version
          gcc --version
      - name: Prepare for building
        run: |
          ./bootstrap.sh
          ./configure --enable-debug --enable-cuckoo --enable-magic
      - name: Build
        run: make clean && make V=1
      - name: Diag
        if: true
        run: |
          set -x
          ls -l
          ls -l .libs/
          file yara
          otool -l ./yara
          otool -L ./yara
          ./yara --version
      - name: Run tests
        run: make check
      - name: Print tests errors
        if: ${{ failure() }}
        run: cat test-suite.log
